// ========================================
// 医学知识图谱 Neo4j 数据模型
// 自动生成于中西医实体三元组数据
// ========================================

// 步骤1: 清空现有数据（可选，生产环境请注释掉）
// MATCH (n) DETACH DELETE n;

// 步骤2: 创建唯一性约束和索引
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Formula) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Herb) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Syndrome) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Symptom) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Disease) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Drug) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:BodyPart) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Treatment) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Examination) REQUIRE n.name IS UNIQUE;

// 步骤3: 创建节点

// 中药材 (Herb) - 27 个节点
MERGE (n:Herb {name: '人参', source: 'chinese'});
MERGE (n:Herb {name: '人参', source: 'western'});
MERGE (n:Herb {name: '党参', source: 'chinese'});
MERGE (n:Herb {name: '党参', source: 'western'});
MERGE (n:Herb {name: '半夏', source: 'chinese'});
MERGE (n:Herb {name: '半夏', source: 'western'});
MERGE (n:Herb {name: '川芎', source: 'chinese'});
MERGE (n:Herb {name: '川芎', source: 'western'});
MERGE (n:Herb {name: '当归', source: 'chinese'});
MERGE (n:Herb {name: '当归', source: 'western'});
MERGE (n:Herb {name: '枸杞', source: 'chinese'});
MERGE (n:Herb {name: '柴胡', source: 'chinese'});
MERGE (n:Herb {name: '柴胡', source: 'western'});
MERGE (n:Herb {name: '甘草', source: 'chinese'});
MERGE (n:Herb {name: '甘草', source: 'western'});
MERGE (n:Herb {name: '白术', source: 'chinese'});
MERGE (n:Herb {name: '白术', source: 'western'});
MERGE (n:Herb {name: '白芍', source: 'chinese'});
MERGE (n:Herb {name: '白芍', source: 'western'});
MERGE (n:Herb {name: '茯苓', source: 'chinese'});
MERGE (n:Herb {name: '茯苓', source: 'western'});
MERGE (n:Herb {name: '黄芩', source: 'chinese'});
MERGE (n:Herb {name: '黄芩', source: 'western'});
MERGE (n:Herb {name: '黄芪', source: 'chinese'});
MERGE (n:Herb {name: '黄芪', source: 'western'});
MERGE (n:Herb {name: '黄连', source: 'chinese'});
MERGE (n:Herb {name: '黄连', source: 'western'});

// 中医证候 (Syndrome) - 19 个节点
MERGE (n:Syndrome {name: '气血不足', source: 'chinese'});
MERGE (n:Syndrome {name: '气血不足', source: 'western'});
MERGE (n:Syndrome {name: '痰湿', source: 'chinese'});
MERGE (n:Syndrome {name: '痰湿', source: 'western'});
MERGE (n:Syndrome {name: '肝火旺盛', source: 'chinese'});
MERGE (n:Syndrome {name: '肝郁', source: 'chinese'});
MERGE (n:Syndrome {name: '肝郁', source: 'western'});
MERGE (n:Syndrome {name: '肾阳虚', source: 'chinese'});
MERGE (n:Syndrome {name: '肾阳虚', source: 'western'});
MERGE (n:Syndrome {name: '肾阴虚', source: 'chinese'});
MERGE (n:Syndrome {name: '肾阴虚', source: 'western'});
MERGE (n:Syndrome {name: '脾气虚', source: 'chinese'});
MERGE (n:Syndrome {name: '脾气虚', source: 'western'});
MERGE (n:Syndrome {name: '脾胃虚弱', source: 'chinese'});
MERGE (n:Syndrome {name: '脾胃虚弱', source: 'western'});
MERGE (n:Syndrome {name: '血瘀', source: 'chinese'});
MERGE (n:Syndrome {name: '血瘀', source: 'western'});
MERGE (n:Syndrome {name: '阴虚火旺', source: 'chinese'});
MERGE (n:Syndrome {name: '阴虚火旺', source: 'western'});

// 症状 (Symptom) - 26 个节点
MERGE (n:Symptom {name: '乏力', source: 'chinese'});
MERGE (n:Symptom {name: '乏力', source: 'western'});
MERGE (n:Symptom {name: '便秘', source: 'chinese'});
MERGE (n:Symptom {name: '便秘', source: 'western'});
MERGE (n:Symptom {name: '出汗', source: 'chinese'});
MERGE (n:Symptom {name: '发热', source: 'chinese'});
MERGE (n:Symptom {name: '发热', source: 'western'});
MERGE (n:Symptom {name: '呕吐', source: 'chinese'});
MERGE (n:Symptom {name: '呕吐', source: 'western'});
MERGE (n:Symptom {name: '咳嗽', source: 'chinese'});
MERGE (n:Symptom {name: '咳嗽', source: 'western'});
MERGE (n:Symptom {name: '失眠', source: 'chinese'});
MERGE (n:Symptom {name: '失眠', source: 'western'});
MERGE (n:Symptom {name: '头晕', source: 'chinese'});
MERGE (n:Symptom {name: '头晕', source: 'western'});
MERGE (n:Symptom {name: '心悸', source: 'chinese'});
MERGE (n:Symptom {name: '心悸', source: 'western'});
MERGE (n:Symptom {name: '恶心', source: 'chinese'});
MERGE (n:Symptom {name: '疼痛', source: 'chinese'});
MERGE (n:Symptom {name: '疼痛', source: 'western'});
MERGE (n:Symptom {name: '胸闷', source: 'chinese'});
MERGE (n:Symptom {name: '胸闷', source: 'western'});
MERGE (n:Symptom {name: '腹泻', source: 'chinese'});
MERGE (n:Symptom {name: '腹泻', source: 'western'});
MERGE (n:Symptom {name: '腹胀', source: 'chinese'});
MERGE (n:Symptom {name: '腹胀', source: 'western'});

// 中医方剂 (Formula) - 14 个节点
MERGE (n:Formula {name: '六味地黄丸', source: 'chinese'});
MERGE (n:Formula {name: '六味地黄丸', source: 'western'});
MERGE (n:Formula {name: '四君子汤', source: 'chinese'});
MERGE (n:Formula {name: '四君子汤', source: 'western'});
MERGE (n:Formula {name: '小柴胡汤', source: 'chinese'});
MERGE (n:Formula {name: '小柴胡汤', source: 'western'});
MERGE (n:Formula {name: '桂枝汤', source: 'chinese'});
MERGE (n:Formula {name: '桂枝汤', source: 'western'});
MERGE (n:Formula {name: '葛根汤', source: 'chinese'});
MERGE (n:Formula {name: '补中益气汤', source: 'chinese'});
MERGE (n:Formula {name: '补中益气汤', source: 'western'});
MERGE (n:Formula {name: '逍遥散', source: 'chinese'});
MERGE (n:Formula {name: '逍遥散', source: 'western'});
MERGE (n:Formula {name: '麻黄汤', source: 'chinese'});

// 西医疾病 (Disease) - 24 个节点
MERGE (n:Disease {name: '心律不齐', source: 'chinese'});
MERGE (n:Disease {name: '心脏病', source: 'chinese'});
MERGE (n:Disease {name: '糖尿病', source: 'chinese'});
MERGE (n:Disease {name: '糖尿病', source: 'western'});
MERGE (n:Disease {name: '肝炎', source: 'chinese'});
MERGE (n:Disease {name: '肝炎', source: 'western'});
MERGE (n:Disease {name: '肝病', source: 'chinese'});
MERGE (n:Disease {name: '肝病', source: 'western'});
MERGE (n:Disease {name: '肠炎', source: 'chinese'});
MERGE (n:Disease {name: '肠炎', source: 'western'});
MERGE (n:Disease {name: '肺炎', source: 'chinese'});
MERGE (n:Disease {name: '肺炎', source: 'western'});
MERGE (n:Disease {name: '肾炎', source: 'chinese'});
MERGE (n:Disease {name: '肾炎', source: 'western'});
MERGE (n:Disease {name: '胃溃疡', source: 'chinese'});
MERGE (n:Disease {name: '胃溃疡', source: 'western'});
MERGE (n:Disease {name: '胃炎', source: 'chinese'});
MERGE (n:Disease {name: '胃炎', source: 'western'});
MERGE (n:Disease {name: '胃病', source: 'chinese'});
MERGE (n:Disease {name: '胃病', source: 'western'});
MERGE (n:Disease {name: '贫血', source: 'chinese'});
MERGE (n:Disease {name: '贫血', source: 'western'});
MERGE (n:Disease {name: '高血压', source: 'chinese'});
MERGE (n:Disease {name: '高血压', source: 'western'});

// 西药 (Drug) - 10 个节点
MERGE (n:Drug {name: '头孢', source: 'chinese'});
MERGE (n:Drug {name: '奥美拉唑', source: 'chinese'});
MERGE (n:Drug {name: '奥美拉唑', source: 'western'});
MERGE (n:Drug {name: '布洛芬', source: 'chinese'});
MERGE (n:Drug {name: '布洛芬', source: 'western'});
MERGE (n:Drug {name: '氯霉素', source: 'chinese'});
MERGE (n:Drug {name: '阿司匹林', source: 'chinese'});
MERGE (n:Drug {name: '阿莫西林', source: 'chinese'});
MERGE (n:Drug {name: '青霉素', source: 'chinese'});
MERGE (n:Drug {name: '青霉素', source: 'western'});

// 总节点数: 120

// 步骤4: 创建关系

// 配伍 (COMBINED_WITH) - 39 条关系
MATCH (a {name: '人参'}), (b {name: '人参'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '甘草'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '白术'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '半夏'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '黄芩'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '当归'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '当归'}) MERGE (a)-[r:COMBINED_WITH {source: 'western'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '当归'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '川芎'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '柴胡'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '黄芪'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '甘草'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '甘草'}) MERGE (a)-[r:COMBINED_WITH {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '当归'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '白术'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '茯苓'}) MERGE (a)-[r:COMBINED_WITH {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '黄芩'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '柴胡'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '白芍'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '茯苓'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '半夏'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '白术'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '茯苓'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '茯苓'}) MERGE (a)-[r:COMBINED_WITH {source: 'western'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '半夏'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '茯苓'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '黄芩'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '黄芪'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '黄连'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '人参'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '党参'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '当归'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '黄芪'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '半夏'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '甘草'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '白芍'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '茯苓'}) MERGE (a)-[r:COMBINED_WITH {source: 'western'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '黄芩'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '黄连'}) MERGE (a)-[r:COMBINED_WITH {source: 'chinese'}]->(b);

// 并发症 (COMPLICATION_OF) - 19 条关系
MATCH (a {name: '糖尿病'}), (b {name: '糖尿病'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '高血压'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '高血压'}) MERGE (a)-[r:COMPLICATION_OF {source: 'western'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '肝炎'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '肺炎'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '肝炎'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '肺炎'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '贫血'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '肾炎'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '贫血'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '高血压'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '胃炎'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '胃炎'}) MERGE (a)-[r:COMPLICATION_OF {source: 'western'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '贫血'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '贫血'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '高血压'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '糖尿病'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '贫血'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '高血压'}) MERGE (a)-[r:COMPLICATION_OF {source: 'chinese'}]->(b);

// 包含 (CONTAINS) - 119 条关系
MATCH (a {name: '六味地黄丸'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '党参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '川芎'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '枸杞'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '黄芪'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '党参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '党参'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '川芎'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '黄芪'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '黄芪'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '党参'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '黄芪'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '川芎'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '黄芪'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '党参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '川芎'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '枸杞'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '黄芪'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '党参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '川芎'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '当归'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '白芍'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '人参'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '半夏'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '川芎'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '柴胡'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '甘草'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '白术'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '茯苓'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '黄芩'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '黄连'}) MERGE (a)-[r:CONTAINS {source: 'chinese'}]->(b);

// 对应 (CORRESPONDS_TO) - 57 条关系
MATCH (a {name: '气血不足'}), (b {name: '糖尿病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '胃炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '贫血'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '贫血'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '糖尿病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '肝炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '肺炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '肝炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '肝病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '胃炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '心脏病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '糖尿病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '肠炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '肠炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '贫血'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '糖尿病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '肝炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '肝病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '贫血'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '肺炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '胃炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '糖尿病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '肝炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '肠炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '肠炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '肺炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '胃溃疡'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '胃炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '胃炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '胃病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '贫血'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '糖尿病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '肝炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '肝病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '肾炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '胃炎'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '胃病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '贫血'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '高血压'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'western'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '糖尿病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '胃病'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '贫血'}) MERGE (a)-[r:CORRESPONDS_TO {source: 'chinese'}]->(b);

// 成分 (HAS_COMPONENT) - 9 条关系
MATCH (a {name: '奥美拉唑'}), (b {name: '黄芪'}) MERGE (a)-[r:HAS_COMPONENT {source: 'western'}]->(b);
MATCH (a {name: '奥美拉唑'}), (b {name: '黄连'}) MERGE (a)-[r:HAS_COMPONENT {source: 'western'}]->(b);
MATCH (a {name: '布洛芬'}), (b {name: '当归'}) MERGE (a)-[r:HAS_COMPONENT {source: 'western'}]->(b);
MATCH (a {name: '氯霉素'}), (b {name: '人参'}) MERGE (a)-[r:HAS_COMPONENT {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '党参'}) MERGE (a)-[r:HAS_COMPONENT {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '川芎'}) MERGE (a)-[r:HAS_COMPONENT {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '柴胡'}) MERGE (a)-[r:HAS_COMPONENT {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '黄芪'}) MERGE (a)-[r:HAS_COMPONENT {source: 'western'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '黄连'}) MERGE (a)-[r:HAS_COMPONENT {source: 'chinese'}]->(b);

// 功效 (HAS_EFFECT_ON) - 137 条关系
MATCH (a {name: '人参'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '党参'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '党参'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '党参'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '党参'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '党参'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '当归'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '当归'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '当归'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '肝火旺盛'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '气血不足'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '脾气虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '血瘀'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '痰湿'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '肝郁'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '肾阳虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '肾阴虚'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '阴虚火旺'}) MERGE (a)-[r:HAS_EFFECT_ON {source: 'western'}]->(b);

// 症候表现 (HAS_SYMPTOM) - 122 条关系
MATCH (a {name: '气血不足'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '腹泻'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '气血不足'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '呕吐'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '恶心'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '胸闷'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '腹泻'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '痰湿'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '呕吐'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '恶心'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '胸闷'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '胸闷'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '腹泻'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肝郁'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '呕吐'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '呕吐'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '胸闷'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '腹泻'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '腹泻'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '肾阳虚'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '胸闷'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '肾阴虚'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '恶心'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '腹泻'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾气虚'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '呕吐'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '恶心'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '胸闷'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '腹泻'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '脾胃虚弱'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '呕吐'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '恶心'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '胸闷'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '血瘀'}), (b {name: '腹胀'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'western'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '乏力'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '便秘'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '发热'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '呕吐'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '咳嗽'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '失眠'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '头晕'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '心悸'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);
MATCH (a {name: '阴虚火旺'}), (b {name: '疼痛'}) MERGE (a)-[r:HAS_SYMPTOM {source: 'chinese'}]->(b);

// 表现为 (MANIFESTS_AS) - 169 条关系
MATCH (a {name: '心律不齐'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心律不齐'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '心脏病'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '出汗'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '糖尿病'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝炎'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肝病'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '肠炎'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肺炎'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '肾炎'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃溃疡'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '出汗'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃炎'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '胃病'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '出汗'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '贫血'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '乏力'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '便秘'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '发热'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '呕吐'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '咳嗽'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '失眠'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '头晕'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '心悸'}) MERGE (a)-[r:MANIFESTS_AS {source: 'western'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '恶心'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '疼痛'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '胸闷'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '腹泻'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);
MATCH (a {name: '高血压'}), (b {name: '腹胀'}) MERGE (a)-[r:MANIFESTS_AS {source: 'chinese'}]->(b);

// 缓解 (RELIEVES) - 29 条关系
MATCH (a {name: '头孢'}), (b {name: '出汗'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '头孢'}), (b {name: '发热'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '头孢'}), (b {name: '呕吐'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '头孢'}), (b {name: '咳嗽'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '头孢'}), (b {name: '恶心'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '头孢'}), (b {name: '疼痛'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '奥美拉唑'}), (b {name: '便秘'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '奥美拉唑'}), (b {name: '恶心'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '奥美拉唑'}), (b {name: '腹胀'}) MERGE (a)-[r:RELIEVES {source: 'western'}]->(b);
MATCH (a {name: '布洛芬'}), (b {name: '乏力'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '布洛芬'}), (b {name: '发热'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '布洛芬'}), (b {name: '头晕'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '布洛芬'}), (b {name: '疼痛'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '布洛芬'}), (b {name: '疼痛'}) MERGE (a)-[r:RELIEVES {source: 'western'}]->(b);
MATCH (a {name: '氯霉素'}), (b {name: '呕吐'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '氯霉素'}), (b {name: '腹胀'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '乏力'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '出汗'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '发热'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '头晕'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '疼痛'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿莫西林'}), (b {name: '发热'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿莫西林'}), (b {name: '咳嗽'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '阿莫西林'}), (b {name: '疼痛'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '发热'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '呕吐'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '咳嗽'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '恶心'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '疼痛'}) MERGE (a)-[r:RELIEVES {source: 'chinese'}]->(b);

// 治疗 (TREATS) - 254 条关系
MATCH (a {name: '人参'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '出汗'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '人参'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '人参'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '党参'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '党参'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '党参'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '糖尿病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '肝炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '肾炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '肾阳虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '肾阴虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '六味地黄丸'}), (b {name: '高血压'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '半夏'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '痰湿'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '肝炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '肝郁'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '肠炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '肾阳虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '胃炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '脾气虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '四君子汤'}), (b {name: '贫血'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '头孢'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '奥美拉唑'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '奥美拉唑'}), (b {name: '胃溃疡'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '气血不足'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '痰湿'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '糖尿病'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '肝炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '肝郁'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '胃炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '胃炎'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '脾气虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '小柴胡汤'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '川芎'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '当归'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '当归'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '枸杞'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '柴胡'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '心律不齐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '糖尿病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '肝郁'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '肠炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '桂枝汤'}), (b {name: '胃炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '氯霉素'}), (b {name: '糖尿病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '氯霉素'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '氯霉素'}), (b {name: '贫血'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '甘草'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '白术'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白术'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '白芍'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '茯苓'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '肠炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '葛根汤'}), (b {name: '高血压'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '气血不足'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '肝炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '肠炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '胃病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '脾气虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '脾胃虚弱'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '补中益气汤'}), (b {name: '贫血'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '肝炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '肝郁'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '肝郁'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '肾阴虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '逍遥散'}), (b {name: '胃炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '心脏病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '肝炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '胃溃疡'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '贫血'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '阿司匹林'}), (b {name: '高血压'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '阿莫西林'}), (b {name: '心脏病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '心脏病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '青霉素'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '痰湿'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '糖尿病'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '肺炎'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '麻黄汤'}), (b {name: '肾阳虚'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芩'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '出汗'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄芪'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'western'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '乏力'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '便秘'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '发热'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '呕吐'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '咳嗽'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '失眠'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '头晕'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '心悸'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '恶心'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '疼痛'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '胸闷'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '腹泻'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);
MATCH (a {name: '黄连'}), (b {name: '腹胀'}) MERGE (a)-[r:TREATS {source: 'chinese'}]->(b);

// 总关系数: 954

// 步骤5: 验证查询示例
// 查询所有节点类型和数量
// MATCH (n) RETURN labels(n) AS NodeType, count(n) AS Count ORDER BY Count DESC;

// 查询所有关系类型和数量
// MATCH ()-[r]->() RETURN type(r) AS RelationType, count(r) AS Count ORDER BY Count DESC;

// 查询特定方剂的完整信息
// MATCH (f:Formula {name: '六味地黄丸'})-[r]-(n) RETURN f, r, n LIMIT 50;

